services:
  mysql-database:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_wordle:/var/lib/mysql
    ports:
      - "3311:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  wordle-backend:
    build: .
    env_file:
      - .env
    ports:
      - "8012:8012"
    depends_on:
      mysql-database:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    volumes:
      - .:/app 

volumes:
  mysql_data_wordle:
